CREATE TABLE stock_overview_rawdata(
    stock_overview_rawdata_id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    symbol varchar NOT NULL, 
    assettype varchar, 
    name varchar, 
    description text, 
    cik varchar, 
    exchange varchar, 
    currency varchar, 
    country varchar, 
    sector varchar, 
    industry varchar, 
    address varchar, 
    fiscalyearend varchar, 
    latestquarter varchar, 
    marketcapitalization int8, 
    ebitda int8, 
    peratio float4, 
    pegratio float4, 
    bookvalue float4, 
    dividendpershare float4, 
    dividendyield float4, 
    eps float4, 
    revenuepersharettm float4, 
    profitmargin float4,
    operatingmarginttm float4,
    returnonassetsttm float4, 
    returnonequityttm float4, 
    revenueTTM int8,
    grossprofitttm int8,
    dilutedepsttm float4, 
    quarterlyearningsgrowthyoy float4, 
    quarterlyrevenuegrowthyoy float4, 
    analysttargetprice float4, 
    trailingpe float4, 
    forwardpe float4, 
    pricetosalesratiottm float4, 
    pricetobookratio float4, 
    evtorevenue float4, 
    evtoebitda float4, 
    beta float4, 
    fiftytwoweekhigh float4,
    fiftytwoweeklow float4,
    fiftydaymovingaverage float4,
    twohundreddaymovingaverage float4,
    sharesoutstanding int8,
    dividenddate varchar,
    exdividenddate varchar, 
    created timestamp default NOW(), 
    updated timestamp default NOW()
)