name: Build Descartes CLI
on:
  push:
    branches:
      - 'main'
      - 'dev/update'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.17' ]
    name: Go ${{ matrix.go }} Descartes CLI
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build Descartes CLI
        run: go build
        working-directory: cli/