name: Build Descartes
on:
  push:
    branches:
      - 'main'
      - 'dev/update'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16' ]
    name: Go ${{ matrix.go }} Descartes
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go build