name: Build Scraper
on:
  push:
    branches:
      - 'main'
      - 'dev/update'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Scraper Docker Build
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Scraper
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./scraper/
          tags: aeekay/descartes-scraper:16 